<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/marco-canas/didactica_ciencia_datos/blob/main/1_curso_machine_learning/1_evaluacion_oral_tarea_quiz_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
  <td>
    <a target="_blank" href="https://kaggle.com/kernels/welcome?src=https://github.com/marco-canas/didactica_ciencia_datos/blob/main/1_curso_machine_learning/1_evaluacion_oral_tarea_quiz_parcial.ipynb"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" /></a>
  </td>
</table>

### [Video de apoyo a la lectura interactiva y experimental de este cuaderno]()

## [Vínculo al programa del curso:  ]()

# Modelo general de clase: [aula invertida](https://www3.gobiernodecanarias.org/medusa/ecoescuela/pedagotic/aprendizaje-invertido-flipped-classroom/)

# Fomento de la lectura literaria asociada a Ingeniería agropecuaria y licenciatura en Matemáticas y administración de empresas

[Hábitos atómicos](https://github.com/marco-canas/habitos_atomicos/blob/main/13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos/1_13_como_dejar_de_postergar_usando_la_regla_de_los_dos_minutos.ipynb)

# Título de la clase: Realización evaluación oral, de Tareas en cuadernos Jupyter, Quiz o Parcial de selección múltiple o de preguntas cerradas.

### Objetivo de aprendizaje (Enunciar, de manera corta sencilla y clara para todos los asistentes)

* [Hipervínculo para el cuaderno de enseñanza]()
1. Evaluar las tareas realizadas de manera manúscrita
2. Evaluar las tareas realizadas en los cuadernos Jupyter. (Solo realizar la tercera parte de las tareas asignadas de manera manuscrita)
3. Evaluar con un quiz escrito
4. Evaluar con un parcial escrito.
5. Evaluar la capacidad de describir un problema y su solución de manera oral.

## Establecimiento de prerrequisitos conceptuales para alcanzar el objetivo de aprendizaje trazado.   

(Elabore una lista de preguntas al rededor de los conceptos que consideres necesarios para empezar la clase).  

1. 
2. 
3.

# Para el diseño de la clase tenga en cuenta algunos problemas de aprendizaje

# Diseño de evaluación oral de si se alcanzaron los objetivos de aprendizaje planteados

* Describa verbalmente el objetivo de aprendizaje y evidencie de forma oral si lo logró o no.

## Cuestionario para realizar labores de memorización, observación y síntesis de la información (Además de diagnóstico)

1. ¿?
2. ¿?
3. ¿?
4. ¿?
5. ¿?

# Vocabulary 

1. length: longitud
2. width: ancho. 

[length, width](https://voca.ro/1of14ffdXnZI)

# 1. Evaluar las tareas realizadas de manera manúscrita
## 2. Evaluar las tareas realizadas en los cuadernos Jupyter. (Solo realizar la tercera parte de las tareas asignadas de manera manuscrita)

In [5]:
# Tarea para antes de realizada la clase
# Consiste en la lectura y completación de un ejemplo del texto guía

import pandas as pd
import numpy as np
import requests
np.random.seed(126)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Example" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
print('Debe transcribir el ejemplo \n en su cuaderno manuscrito y Jupyter y completar los procedimientos')
assignment_df

Tarea asignada:  tarea_Purcell_Página_202_Sección_3.8.csv
Debe transcribir el ejemplo
 en su cuaderno manuscrito y Jupyter y completar los procedimientos

                              Student  Example1
0        AGUDELO MORENO RENATO DIRNEY        39
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         2
2       ARENAS HERAZO GABRIEL ENRIQUE        37
3        AYALA MENDOZA MARISOL YACIRA         4
4          BERTEL RODELO MICHELL SMIT        12
5            BULA VERGARA MARIA PAULA        51
6             CANTILLO ENSUCHO DANIEL         5
7            CERVANTES DURAN ANGELICA        49
8         GALLEGO TEJADA JUAN ESTEBAN        28
9             GUERRA NORIEGA YONATHAN        33
10    HINCAPIE CASTRO JOHAN SEBASTIAN        27
11             HUMANEZ SANCHEZ CAMILO        46
12       IBAnEZ MORENO FRANCISCO LUIS        26
13  LONDONO CUADRADO CRISTIAN ALBERTO        42
14          MASS MIRANDA RIVALDO JOSE        16
15     MIRANDA MARTINEZ CARLOS ANDRES        46
16              MONTERROSA SOTO ABRIL        30
17           NORIEGA JIMENEZ GABRIELA        50
18             PEREZ REYES IVAN DARIO        15
19               PEREZ THERAN ERLINDA        46
20              PINEDA ROMERO YOSMERI        17
21         QUINONEZ CERVANTES MARIANA        23
22           QUIROZ DURAN JUAN MANUEL        38
23                 RAMOS PEREZ YANINE        35
24              RIVAS HOYOS ESTEFANIA        10
25              ROSILLO TEJADA VANESA        29
26          SANCHEZ PADILLA SILVESTRE        46
27        SILVA ROYERO MAILY CRISTINA         3
28          USUGA GEORGE JHON ESTIVEN        29

In [6]:
# Tarea: Asignación de ejercicio para realizar en clase


import pandas as pd
import numpy as np
import requests
np.random.seed(424)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exer" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
assignment_df

Tarea asignada:  tarea_Purcell_Página_202_Sección_3.8.csv

                              Student  Exer1
0        AGUDELO MORENO RENATO DIRNEY     47
1   AMARIS FERNANDEZ SEBASTIAN CAMILO     42
2       ARENAS HERAZO GABRIEL ENRIQUE     45
3        AYALA MENDOZA MARISOL YACIRA     24
4          BERTEL RODELO MICHELL SMIT      9
5            BULA VERGARA MARIA PAULA     34
6             CANTILLO ENSUCHO DANIEL      2
7            CERVANTES DURAN ANGELICA     46
8         GALLEGO TEJADA JUAN ESTEBAN     19
9             GUERRA NORIEGA YONATHAN     54
10    HINCAPIE CASTRO JOHAN SEBASTIAN     47
11             HUMANEZ SANCHEZ CAMILO      5
12       IBAnEZ MORENO FRANCISCO LUIS     25
13  LONDONO CUADRADO CRISTIAN ALBERTO      4
14          MASS MIRANDA RIVALDO JOSE     19
15     MIRANDA MARTINEZ CARLOS ANDRES     15
16              MONTERROSA SOTO ABRIL      5
17           NORIEGA JIMENEZ GABRIELA     10
18             PEREZ REYES IVAN DARIO     39
19               PEREZ THERAN ERLINDA     52
20              PINEDA ROMERO YOSMERI      6
21         QUINONEZ CERVANTES MARIANA     17
22           QUIROZ DURAN JUAN MANUEL      7
23                 RAMOS PEREZ YANINE     14
24              RIVAS HOYOS ESTEFANIA     11
25              ROSILLO TEJADA VANESA     18
26          SANCHEZ PADILLA SILVESTRE     25
27        SILVA ROYERO MAILY CRISTINA      4
28          USUGA GEORGE JHON ESTIVEN     47

In [9]:
# Tarea para después de la clase: asignación de ejercicios de un seccion del texto guía

# Tarea para adquisición de habilidades


import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 10


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Exer" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
assignment_df

Tarea asignada:  tarea_Purcell_Página_202_Sección_3.8.csv

,Student,Exer1,Exer2,Exer3,Exer4,Exer5,Exer6,Exer7,Exer8,Exer9,Exer10
0,AGUDELO MORENO RENATO DIRNEY,48,22,2,50,53,54,17,33,15,7
1,AMARIS FERNANDEZ SEBASTIAN CAMILO,37,18,20,42,28,43,11,6,46,24
2,ARENAS HERAZO GABRIEL ENRIQUE,29,47,49,33,26,20,48,39,23,5
3,AYALA MENDOZA MARISOL YACIRA,45,35,7,48,26,38,23,24,44,41
4,BERTEL RODELO MICHELL SMIT,41,14,29,16,25,4,42,28,20,49
5,BULA VERGARA MARIA PAULA,22,46,5,10,21,2,12,44,19,11
6,CANTILLO ENSUCHO DANIEL,19,50,46,14,48,12,13,16,32,39
7,CERVANTES DURAN ANGELICA,16,20,13,24,6,3,14,8,27,52
8,GALLEGO TEJADA JUAN ESTEBAN,36,11,49,47,37,15,5,20,42,24
9,GUERRA NORIEGA YONATHAN,47,43,51,6,46,10,26,35,22,32
10,HINCAPIE CASTRO JOHAN SEBASTIAN,35,51,2,33,18,46,37,31,4,38
11,HUMANEZ SANCHEZ CAMILO,20,26,50,33,28,19,47,4,13,41
12,IBAnEZ MORENO FRANCISCO LUIS,7,8,53,19,15,41,51,24,45,50
13,LONDONO CUADRADO CRISTIAN ALBERTO,37,10,6,44,5,8,47,39,9,15
14,MASS MIRANDA RIVALDO JOSE,35,14,23,13,27,22,17,41,42,46
15,MIRANDA MARTINEZ CARLOS ANDRES,11,30,29,48,54,47,35,16,19,8
16,MONTERROSA SOTO ABRIL,10,8,4,37,15,16,3,6,25,45
17,NORIEGA JIMENEZ GABRIELA,2,41,37,27,50,20,4,22,3,53
18,PEREZ REYES IVAN DARIO,6,13,34,2,36,14,22,30,49,33
19,PEREZ THERAN ERLINDA,49,4,47,29,27,22,38,39,32,19
20,PINEDA ROMERO YOSMERI,42,9,2,31,48,13,53,47,46,39
21,QUINONEZ CERVANTES MARIANA,11,49,32,13,40,29,38,10,28,18
22,QUIROZ DURAN JUAN MANUEL,43,14,21,40,44,3,2,33,39,20
23,RAMOS PEREZ YANINE,7,27,47,13,50,9,8,4,20,21
24,RIVAS HOYOS ESTEFANIA,23,27,39,47,53,33,28,6,31,46
25,ROSILLO TEJADA VANESA,49,11,16,4,37,19,28,9,30,53
26,SANCHEZ PADILLA SILVESTRE,25,37,50,16,2,22,14,23,43,24
27,SILVA ROYERO MAILY CRISTINA,11,25,2,47,22,42,16,8,50,18
28,USUGA GEORGE JHON ESTIVEN,29,20,12,44,52,28,7,4,15,53


# 3. Evaluar con un quiz escrito

In [10]:
# Quiz escrito: 



import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 2


# Asignar ejercicios aleatorios a cada estudiante

random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+1 
random_exercises

array([48, 22])

4. Evaluar con un parcial escrito.

In [11]:
# Parcial escrito: 



import pandas as pd
import numpy as np
import requests
np.random.seed(1213)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 5


# Asignar ejercicios aleatorios a cada estudiante

random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+1 
random_exercises

array([48, 22,  2, 50, 53])

# 5. Evaluación oral
## 5. Evaluar la capacidad de describir un problema y su solución de manera oral. 

1. Evaluaremos la capacidad de describir cada uno de los pasos o fases para resolver un problema (Es decir, se pedirá al estudiante que describa la metodología de solución de un problema dado).

In [12]:
# Llamar a lista o tomar asistencia con python 

import pandas as pd # convertir la lista de estudiantes en un dataframe
import numpy as np # elección aleatoria

# Cargar la lista de estudiantes desde la URL
url = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/english.csv'
estudiantes = pd.read_csv(url) # convierte el csv en una dataframe

# Convertir la columna 'Nombre' a una lista de Python
lista_estudiantes = estudiantes['Nombre'].tolist()

# Función para llamar a un estudiante aleatoriamente y registrar su nota de seguimiento
def llamar_estudiante():
    if lista_estudiantes:
        estudiante_aleatorio = np.random.choice(lista_estudiantes)
        print(f"Llamando a {estudiante_aleatorio}...")
        lista_estudiantes.remove(estudiante_aleatorio)
    else:
        print("Se han llamado a todos los estudiantes del grupo completo.")

In [13]:
llamar_estudiante()

Llamando a Maro Julio Canas...

In [14]:

# Tarea para antes de realizada la clase
# Consiste en la lectura y completación de un ejemplo del texto guía

import pandas as pd
import numpy as np
import requests
np.random.seed(126)  # establecer semilla aleatoria para hacer los resultados reproducibles



grupo_estudiantes = 'calculo_integral'
nombre_texto_guia = 'Purcell'
pagina_y_seccion = 'Página_202_Sección_3.8'
numero_ejercicios_taller = 54
numero_de_ejercicios_asignados = 1


# Descargar la lista de  estudiantes
students_url = "https://raw.githubusercontent.com/marco-canas/groups_list/main/" + grupo_estudiantes + ".csv"
exercises = list(range(1, numero_ejercicios_taller))  

students_data = pd.read_csv(students_url)

# Crear una lista para almacenar las asignaciones
assignments = []

# Asignar ejercicios aleatorios a cada estudiante
for index, student in students_data.iterrows():
    # Seleccionar 5 ejercicios aleatorios sin repetición
    random_exercises = np.random.choice(exercises, numero_de_ejercicios_asignados, replace = False)+ 1 
    assignments.append([students_data["Nombre"][index], *random_exercises])  # Agregar asignación a la lista

# Crear un DataFrame con las asignaciones
columns = ["Student"] + [ "Example" + str(i+1) for i in range(numero_de_ejercicios_asignados)]
assignment_df = pd.DataFrame(assignments, columns=columns)

# Guardar el DataFrame en un archivo CSV
assignment_csv = "tarea" + "_" + nombre_texto_guia + "_"+ pagina_y_seccion + ".csv"
assignment_df.to_csv(assignment_csv, index=False)

print("Tarea asignada: ", assignment_csv)
print('Debe transcribir el ejemplo \n en su cuaderno manuscrito y Jupyter y completar los procedimientos')
assignment_df

Tarea asignada:  tarea_Purcell_Página_202_Sección_3.8.csv
Debe transcribir el ejemplo
 en su cuaderno manuscrito y Jupyter y completar los procedimientos

                              Student  Example1
0        AGUDELO MORENO RENATO DIRNEY        39
1   AMARIS FERNANDEZ SEBASTIAN CAMILO         2
2       ARENAS HERAZO GABRIEL ENRIQUE        37
3        AYALA MENDOZA MARISOL YACIRA         4
4          BERTEL RODELO MICHELL SMIT        12
5            BULA VERGARA MARIA PAULA        51
6             CANTILLO ENSUCHO DANIEL         5
7            CERVANTES DURAN ANGELICA        49
8         GALLEGO TEJADA JUAN ESTEBAN        28
9             GUERRA NORIEGA YONATHAN        33
10    HINCAPIE CASTRO JOHAN SEBASTIAN        27
11             HUMANEZ SANCHEZ CAMILO        46
12       IBAnEZ MORENO FRANCISCO LUIS        26
13  LONDONO CUADRADO CRISTIAN ALBERTO        42
14          MASS MIRANDA RIVALDO JOSE        16
15     MIRANDA MARTINEZ CARLOS ANDRES        46
16              MONTERROSA SOTO ABRIL        30
17           NORIEGA JIMENEZ GABRIELA        50
18             PEREZ REYES IVAN DARIO        15
19               PEREZ THERAN ERLINDA        46
20              PINEDA ROMERO YOSMERI        17
21         QUINONEZ CERVANTES MARIANA        23
22           QUIROZ DURAN JUAN MANUEL        38
23                 RAMOS PEREZ YANINE        35
24              RIVAS HOYOS ESTEFANIA        10
25              ROSILLO TEJADA VANESA        29
26          SANCHEZ PADILLA SILVESTRE        46
27        SILVA ROYERO MAILY CRISTINA         3
28          USUGA GEORGE JHON ESTIVEN        29

# Programa para evaluación del seguimiento mensual de los estudiantes

In [7]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

#weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weightHandwrittenNotebook = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/seminario_didactica_aritmetica.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.HandwrittenNotebook = (df.HandwrittenNotebook/np.max(df.HandwrittenNotebook))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = df.Assistance*weightAssistance + \
                 df.AttentionParticipation*weightAttentionParticipation + \
                 df.HandwrittenNotebook*weightHandwrittenNotebook+\
                 df.JupyterNotebook*weightJupyterNotebook+\
                 df.Quiz*weightQuiz + \
                 df.Partial*weightPartial

df.FollowUp = df.FollowUp.round(1)

df[['Nombre', 'FollowUp']]

AttributeError: 'DataFrame' object has no attribute 'AttentionParticipation'

<img src = ''>

## Estrategias propuestas para la solución de las dificultades de aprendizaje detectadas

## Cuestionario para realizar labores de memorización y observación,  a la síntesis de la información

## Grabaciones en audio para fomentar la capacidad de memorizar enunciados de teoremas y resultados científicos y la capacidad de parafrasear estos resultados.

Se dispondrá de un lugar en el drive asociuado al correo institucional de la Universidad Nacional del Profesor Marso para albergar los archivosd de audio de fomento a la memoirización, enunciación y parafraseo de los resultados científicos, prtopiedades, reglas, etc. 

* Vocaroo

### Comparta sus cuadernos y videos, evidencias de su aprendizaje [aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUMEMwTEZVMzEwVVBPTElWNVg5OVEyWUhMUy4u)

# FODA del grupo y del profesor  

* F: Fortalezas
* O: Oportunidades
* D: Dificultades
* A: Amenazas.

## ¿Cómo se sintió en este espacio de enseñanza y aprendizaje?

!Dios te bendiga¡

In [15]:
# Programa para valoración cuantitativa por meses para los estudiantes de todos los cursos
import numpy as np 
import pandas as pd   

# Weights
weightAssistance = 12/100
weightAttentionParticipation = 8/100
weight_tast_1_2_3 = 8/100
weightJupyterNotebook = 20/100
weightQuiz = 16/100
weightPartial = 48/100

url_group = 'https://raw.githubusercontent.com/marco-canas/groups_list/main/calculo_integral.csv'

df = pd.read_csv(url_group, decimal = ',') 

df.Assistance = (df.Assistance/np.max(df.Assistance))*5.0
df.AttentionParticipation = (df.AttentionParticipation/np.max(df.AttentionParticipation))*5.0
df.task_1_2_3 = (df.task_1_2_3/np.max(df.task_1_2_3))*5.0
df.JupyterNotebook = (df.JupyterNotebook/np.max(df.JupyterNotebook))*5.0  


df['FollowUp'] = np.round(df.Assistance*weightAssistance+\
    df.AttentionParticipation*weightAttentionParticipation+\
    df.HandwrittenNotebook*weight_task_1_2_3+\
    df.JupyterNotebook*weightJupyterNotebook+\
    df.Quiz*weightQuiz+\
    df.Partial*weightPartial,1)
df[['Nombre', 'FollowUp']]

                               Nombre  FollowUp
0        AGUDELO MORENO RENATO DIRNEY       2.8
1   AMARIS FERNANDEZ SEBASTIAN CAMILO       2.5
2       ARENAS HERAZO GABRIEL ENRIQUE       2.5
3        AYALA MENDOZA MARISOL YACIRA       2.7
4          BERTEL RODELO MICHELL SMIT       2.5
5            BULA VERGARA MARIA PAULA       2.5
6             CANTILLO ENSUCHO DANIEL       5.0
7            CERVANTES DURAN ANGELICA       3.4
8         GALLEGO TEJADA JUAN ESTEBAN       1.9
9             GUERRA NORIEGA YONATHAN       4.6
10    HINCAPIE CASTRO JOHAN SEBASTIAN       3.8
11             HUMANEZ SANCHEZ CAMILO       4.7
12       IBAnEZ MORENO FRANCISCO LUIS       3.5
13  LONDONO CUADRADO CRISTIAN ALBERTO       2.0
14       LOZANO HOLGUIN LIZETH JOHANA       3.4
15          MASS MIRANDA RIVALDO JOSE       4.6
16     MIRANDA MARTINEZ CARLOS ANDRES       3.8
17              MONTERROSA SOTO ABRIL       2.6
18           NORIEGA JIMENEZ GABRIELA       2.2
19             PEREZ REYES IVAN DARIO       2.3
20               PEREZ THERAN ERLINDA       2.8
21              PINEDA ROMERO YOSMERI       4.1
22         QUINONEZ CERVANTES MARIANA       2.4
23           QUIROZ DURAN JUAN MANUEL       1.8
24                 RAMOS PEREZ YANINE       2.7
25              RIVAS HOYOS ESTEFANIA       2.3
26              ROSILLO TEJADA VANESA       4.8
27          SANCHEZ PADILLA SILVESTRE       4.8
28        SILVA ROYERO MAILY CRISTINA       2.1
29          USUGA GEORGE JHON ESTIVEN       3.9

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Nombre                  30 non-null     object
 1   Email                   30 non-null     object
 2   AttentionParticipation  30 non-null     float64
 3   JupyterNotebook         30 non-null     float64
 4   Partial                 30 non-null     float64
 5   Quiz                    30 non-null     float64
 6   HandwrittenNotebook     30 non-null     float64
 7   Assistance              30 non-null     float64
dtypes: float64(6), object(2)
memory usage: 2.0+ KB

## Referentes

* [stewart precálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ERHIq62I6qFNrmxy6LZb8ZMBci7kUsyNME1nIh9yCBMJ_w?e=0zMSla)  

* [stewart cálculo](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EZgXZjAp8QxPqOAim2hs6LcBNPLGjSHf-xwYnUVYkwa04w?e=RZdTCy)  

* [larson](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ES71ChFeO9ZDhW3TwC5Ijk8BjxUK3Pdqz_fjHxTTFAfIAg?e=VDEjfu)

* [uzcategui](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/ETDikm-lVl1Or8XoEo9oyh0BEti9Zs8le-f0D-dBdtZmbA?e=bBsoyQ)

* [Recomendación de la UNESCO sobre ciencia abierta](https://unesdoc.unesco.org/ark:/48223/pf0000379949_spa)  

* [chatGPT](https://openai.com/blog/chatgpt)  

* Géron, A. (2017). Hands-on machine learning with scikit-learn and tensorflow: Concepts. Tools, and Techniques to build intelligent systems.[Geron, Aurelien. Hands on Machine Learning](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/Ecet27yjQzZIlT1Y_Bc2erkBUhbeYuIe6HG8i1FYZRlZww?e=dlvZ4v)  

* McKinney, W. (2012). Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. " O'Reilly Media, Inc.".[Wes Mackinney. ](https://udeaeduco-my.sharepoint.com/:b:/g/personal/marco_canas_udea_edu_co/EVbi5JIeBl9ErbiUnZfGe8YBhNTnZ8sxTK5hjIOPK4UpGw?e=fFclah)

### [Evaluamos al profesor Marco Cañas Aquí](https://forms.office.com/Pages/ResponsePage.aspx?id=IefhmYRxjkmK_7KtTlPBwkanXIs1i1FEujpsZgO6dXpUREJPV1kxUk1JV1ozTFJIQVNIQjY5WEY3US4u)

## [Evaluación luego de alcanzar estos objetivos de aprendizaje]()

### Continue su aprendizaje en la siguiente clase a través del siguiente [vínculo]()

# Conjeturas pedagógicas fruto de la aplicación del modelo de aprendizaje invertido y del enfoque hacia la ciencia de datos con python

1. Todo cálculo o resultado debe ser interpretado en una línea markdown del cuaderno Jupyter, inmediatamente después de la enunciación del resultado y después de la presentación de una tabla o gráfico bidimensional, de tal menera que el estudiante explicite la comprensión verbal del resultado y las inferencias o estrategias que este resultado le sugieren.